import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
/**
*@ClassName:LoansWindow
*@Description:LoansWindow File contains LoansWindow class and form.
 * It prompts a window which has a request loan button and the rules for requesting a loan.
*@Author:Yuesi Liu, Zhaoyu Yin, Xinlong Zhang
*@Date:12/14/2021
*@Version: Final
*
*/

public class LoansWindow extends JFrame implements Window {
    private JPanel LoansWindow;
    private JScrollPane loansScroll;
    private JPanel loansPanel;
    private JButton requestLoanButton;
    private JLabel LoanLabel;
    private JButton refreshButton;
    private ATM atmsystem;

    public LoansWindow(CustomerWindow customerWindow, ATM atm) {

        WindowSetter.windowConfig2(this, LoansWindow);
        this.atmsystem = atm;
        LoanLabel.setText("Each loan will be charged an interest " + Constants.Loan_Interest_Percentage + "% each month");
        reFresh();

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                customerWindow.setVisible(true);
            }
        });

        requestLoanButton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                new RequestLoanDialog(atmsystem);
                reFresh();
            }
        });
    }

    public void reFresh() {
        loansPanel.setLayout(new BoxLayout(loansPanel, BoxLayout.Y_AXIS));
        ((Customer) atmsystem.getUser()).updatedLoans();
        List<Loan> ls = ((Customer) atmsystem.getUser()).getLoans();
        loansPanel.removeAll();
        for (Loan l : ls) {
            LoanElement e = new LoanElement(atmsystem, l, this);
            loansPanel.add(e.$$$getRootComponent$$$());
        }
        loansPanel.revalidate();
        loansPanel.repaint();
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        LoansWindow = new JPanel();
        LoansWindow.setLayout(new GridLayoutManager(2, 1, new Insets(20, 20, 20, 20), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        LoansWindow.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        LoanLabel = new JLabel();
        LoanLabel.setText("Loan charge fee rules");
        panel1.add(LoanLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel1.add(spacer1, new GridConstraints(0, 2, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        requestLoanButton = new JButton();
        requestLoanButton.setText("Request a loan");
        panel1.add(requestLoanButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        panel1.add(spacer2, new GridConstraints(1, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        loansScroll = new JScrollPane();
        LoansWindow.add(loansScroll, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        loansPanel = new JPanel();
        loansPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        loansScroll.setViewportView(loansPanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return LoansWindow;
    }

}
