import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
/**
*@ClassName:TransactionWindow
*@Description:TransactionWindow File contains TransactionWindow class and form. It prompts a window for users to start
 * a transaction.
*@Author:Yuesi Liu, Zhaoyu Yin, Xinlong Zhang
*@Date:12/14/2021
*@Version: Final
*
*/

public class TransactionWindow extends JFrame implements Window {
    private JPanel TransactionWindow;
    private JScrollPane transactionScroll;
    private JPanel transactionPanel;
    private ATM atmsystem;

    public TransactionWindow(CustomerWindow customerWindow, ATM atm) {
        WindowSetter.windowConfig2(this, TransactionWindow);
        this.atmsystem = atm;
        reFresh();
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                customerWindow.setVisible(true);
            }
        });

    }

    public void reFresh() {
        transactionPanel.setLayout(new BoxLayout(transactionPanel, BoxLayout.Y_AXIS));
        List<Transaction> ts = ((Customer) atmsystem.getUser()).getHisTransactions();
        transactionPanel.removeAll();
        for (Transaction t : ts) {
            TransactionElement e = new TransactionElement(atmsystem, t);
            transactionPanel.add(e.$$$getRootComponent$$$());
        }
        transactionPanel.revalidate();
        transactionPanel.repaint();
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        TransactionWindow = new JPanel();
        TransactionWindow.setLayout(new GridLayoutManager(1, 1, new Insets(20, 20, 20, 20), -1, -1));
        transactionScroll = new JScrollPane();
        transactionScroll.setVerticalScrollBarPolicy(22);
        TransactionWindow.add(transactionScroll, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        transactionPanel = new JPanel();
        transactionPanel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        transactionScroll.setViewportView(transactionPanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return TransactionWindow;
    }

}
